In [81]:
import numpy as np
import random

In [82]:
a=np.zeros(5)
print(a)
print(a.shape)
print(a.size)
print(a.itemsize)

[0. 0. 0. 0. 0.]
(5,)
5
8


In [90]:
w=np.ones((5,4))
print(w)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [84]:
a=np.arange(1,21).reshape(4,5)
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [85]:
print(a*10)

[[ 10  20  30  40  50]
 [ 60  70  80  90 100]
 [110 120 130 140 150]
 [160 170 180 190 200]]


In [86]:
m=a[a%2!=0]
print(m)

[ 1  3  5  7  9 11 13 15 17 19]


In [109]:
s=list()
q=np.arange(1,21)
for i in q:
    if (i%2==0):
        s.append(-i)
    else:
        s.append(i)
print(s)

[1, -2, 3, -4, 5, -6, 7, -8, 9, -10, 11, -12, 13, -14, 15, -16, 17, -18, 19, -20]


In [103]:
j = list()
m = np.arange(1,21)
for i in m:
    if(i%2 == 0):
        j.append(i * -1)
    else:
        j.append(i)
print(j)

[1, -2, 3, -4, 5, -6, 7, -8, 9, -10, 11, -12, 13, -14, 15, -16, 17, -18, 19, -20]


In [111]:
M1=np.arange(1,17).reshape(4,4)
print(M1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [120]:
M2=M1.T
print(M2)
print()
#or
M2=M1.transpose()
print(M2)

[[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]

[[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]


In [121]:
M3=M1+M2
print(M3)

[[ 2  7 12 17]
 [ 7 12 17 22]
 [12 17 22 27]
 [17 22 27 32]]


In [122]:
MT1=M3.T
print(MT1)

[[ 2  7 12 17]
 [ 7 12 17 22]
 [12 17 22 27]
 [17 22 27 32]]


In [136]:
print((MT1==M3).all())

True


In [128]:
M4=M1-M2
print(M4)

[[ 0 -3 -6 -9]
 [ 3  0 -3 -6]
 [ 6  3  0 -3]
 [ 9  6  3  0]]


In [129]:
MT2=M4.T
print(MT2)

[[ 0  3  6  9]
 [-3  0  3  6]
 [-6 -3  0  3]
 [-9 -6 -3  0]]


In [135]:
print((M4==MT2).all())
print()
print((M4==-MT2).all())

False

True


In [159]:
R1=np.random.randint(10,40,12).reshape(3,4)
print(R1)

[[24 29 13 12]
 [11 15 13 24]
 [36 17 30 24]]


In [155]:
xmin = np.amin(R1,axis = 0)
print(xmin)
print()
xmax = np.amax(R1,axis = 0)
print(xmax)

[11 24 23 12]

[37 39 30 39]


In [160]:
n = np.sum(R1[:,:3], axis = 0)
R1[:,3] = n
print(R1)

[[24 29 13 71]
 [11 15 13 61]
 [36 17 30 56]]


In [156]:
z=list()
R1=np.random.randint(10,40,12)
print(R1)
for i in R1:
    if (i%2==0):
        z.append(np.nan)
    else:
        z.append(i)
print(z)

[13 27 24 24 27 25 31 28 28 20 38 19]
[13, 27, nan, nan, 27, 25, 31, nan, nan, nan, nan, 19]


In [157]:
c=z.count(np.NaN)
print(c)

6


In [163]:
a1 = np.arange(1,10).reshape(3,3)
a2 = np.arange(11,20).reshape(3,3)
a3 = np.append(a1,a2)
print(a3)
print()
a3 = np.append(a1,a2, axis = 0)
print(a3)
print()
a3 = np.append(a1,a2, axis = 1)
print(a3)

[ 1  2  3  4  5  6  7  8  9 11 12 13 14 15 16 17 18 19]

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12 13]
 [14 15 16]
 [17 18 19]]

[[ 1  2  3 11 12 13]
 [ 4  5  6 14 15 16]
 [ 7  8  9 17 18 19]]
